global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets:
          - nodeexporter:9100
  - job_name: 'postgres'
    static_configs:
      - targets:
          - postgresexporter:9187
  - job_name: 'nginx'
    static_configs:
      - targets:
          - nginxexporter:9113
