global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    monitor: 'my-project'
scrape_configs:
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets:
          - nodeexporter:9100
  - job_name: 'postgres'
    scrape_interval: 5s
    static_configs:
      - targets:
          - postgresexporter:9187
  - job_name: 'nginx'
    scrape_interval: 5s
    static_configs:
      - targets:
          - nginxexporter:9113
